#!/bin/bash

set -x

# This script downloads tiles from NASA + NOAA and uploads them to S3. It is
# meant to be run locally on your machine, but there's no reason to run it
# multiple times unless the contents of S3 were corrupted.
#
# We can't download tiles from the ECS containers because NASA blocks downloads
# from AWS IPs, and it's better to be a good citizen and not put too much
# burden on public servers. :)

upload_blue_marble_tileset() {
    wget -O a1.jpg "$2.A1.jpg"
    wget -O a2.jpg "$2.A2.jpg"
    wget -O b1.jpg "$2.B1.jpg"
    wget -O b2.jpg "$2.B2.jpg"
    wget -O c1.jpg "$2.C1.jpg"
    wget -O c2.jpg "$2.C2.jpg"
    wget -O d1.jpg "$2.D1.jpg"
    wget -O d2.jpg "$2.D2.jpg"

    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp a1.jpg s3://$OUTPUT_BUCKET_NAME/$1/a1.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp a2.jpg s3://$OUTPUT_BUCKET_NAME/$1/a2.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp b1.jpg s3://$OUTPUT_BUCKET_NAME/$1/b1.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp b2.jpg s3://$OUTPUT_BUCKET_NAME/$1/b2.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp c1.jpg s3://$OUTPUT_BUCKET_NAME/$1/c1.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp c2.jpg s3://$OUTPUT_BUCKET_NAME/$1/c2.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp d1.jpg s3://$OUTPUT_BUCKET_NAME/$1/d1.jpg
    aws --endpoint-url $AWS_ENDPOINT_URL s3 cp d2.jpg s3://$OUTPUT_BUCKET_NAME/$1/d2.jpg

    rm a1.jpg a2.jpg
    rm b1.jpg b2.jpg
    rm c1.jpg c2.jpg
    rm d1.jpg d2.jpg
}

upload_blue_marble_tileset "raw/winter" "https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73909/world.topo.bathy.200412.3x21600x21600"
upload_blue_marble_tileset "raw/spring" "https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73630/world.topo.bathy.200403.3x21600x21600"
upload_blue_marble_tileset "raw/summer" "https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73726/world.topo.bathy.200406.3x21600x21600"
upload_blue_marble_tileset "raw/autumn" "https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73801/world.topo.bathy.200409.3x21600x21600"
