version: 2
jobs:
  publish_stage:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo pip install --upgrade awscli==1.15.4
      - run: $(AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY aws ecr get-login --no-include-email)
      - run: make push-stage
workflows:
  version: 2
  publish:
    jobs:
      - publish_stage:
          filters:
            branches:
              only: master
